name = "statistical_rethinking"
uuid = "77d4adeb-c15b-4d56-a94c-42c342f68965"
authors = ["Lukas Grassauer <lukas@grassauer.eu> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatisticalRethinking = "2d09df54-9d0f-5258-8220-54c2a3d4fbee"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
